### ISSUE TITLE
Add CAMEMBERT configurations

### ISSUE THREAD

**Issue by dennissergeev** [exoclim/lfric_dev#11]
Set up [CAMEMBERT](https://doi.org/10.3847/PSJ/ac9dfe) cases.

- [x] Create an lfric-apps ticket: [#943](https://code.metoffice.gov.uk/trac/lfric_apps/ticket/943)
- [x] Add spectral files for Case 3 (SOCRATES [Ticket #172](https://code.metoffice.gov.uk/trac/socrates/ticket/172))
- [ ] Add spectral files for Case 2 (SOCRATES [Ticket #191](https://code.metoffice.gov.uk/trac/socrates/ticket/191))
- [x] Fix the ANTS environment - **use UG-ANTS**
- [x] Create the input file for K2-18b
- [x] GJ 1214b Case 1 - `u-dr931`
- [x] GJ 1214b Case 2 - `u-dr817`
- [x] GJ 1214b Case 3 - on rose-stem and `u-dr647`
- [x] K2-18b Case 1 - `u-dr931`
- [x] K2-18b Case 2 - `u-dr817`
- [x] K2-18b Case 3 - `u-dr647`
- [ ] Add more cases to rose-stem?

**Comment by dennissergeev** [comment]
Input data for Case 3 are in `/home/links/ds591/exoplanets/lfric_hj_bench_proj/data/ancil/lfric` on EPIC
